name: clownine

on:
  repository_dispatch:
    types: do-something
  workflow_dispatch:
  push:
  schedule:
  - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          
      - name: Setup Git
        run: |
            git config --global user.email ${{ secrets.EMAIL }}
            git config --global user.name ${{ secrets.USERNAME }}
            git config --global credential.helper store
            echo "https://${{ secrets.USERNAME }}:${{ secrets.TOKEN }}@github.com" > ~/.git-credentials
        shell: bash
      
      - name: Executing Scripts
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install dependencies
        run: npm install
      - name: Run main.js
        run: node main.js
      - name: Commit changes
        run: |
          git remote remove origin
          git remote add origin https://${{ secrets.TOKEN }}@github.com/${{ secrets.USERNAME }}/eminaenin
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main
          
      - name: Purge Commit History
        run: |
          git checkout --orphan latest_branch
          git add -A && git commit -am "syek!"
          git branch -D main && git branch -m main
          git push -f origin main      
        
      
           
      

      
      
