name: clownine

on:
  repository_dispatch:
    types: do-something
  workflow_dispatch:
  push:
  schedule:
  - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          
      - name: Setup Git
        
        shell: bash
      
      - name: Executing Scripts
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install dependencies
        run: npm install
        
      - name: Run main.js
        run: node main.js
        
      - name: Commit changes
        run: |
          git commit -a -m "Add changes"
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        
      
           
      

      
      
